import { Attachment, Message, ReplyPreview } from "../types";
import { Avatar } from "./avatar";
import { FormattedText } from "./formatted-text";

// Build a one-line label for a parent message that has no usable text body —
// either a new send (empty text) or a legacy "[GIF] {title}" caption from the
// pre-GIPHY sender path. We surface attachment.name when the source ships
// something descriptive (GIPHY title, image filename, file name) and fall
// back to a generic kind label otherwise. Voice intentionally never shows
// the underlying filename — it's always an autogenerated "voice-{ts}.webm".
function attachmentLabel(att: Attachment): string {
  if (att.type === "voice") return "🎤 Voice";
  if (att.type === "file") return `📎 ${att.name}`;
  // Heuristic GIF detection — covers both paths into the system: GIPHY
  // (host match) and manual .gif uploads (extension on url or name).
  // Interim until Attachment.type grows a "gif" variant.
  const url = att.url ?? "";
  const name = att.name ?? "";
  const isGif =
    url.includes("giphy.com") ||
    /\.gif(\?|$)/i.test(url) ||
    /\.gif$/i.test(name);
  if (isGif) return `🖼 ${att.name || "GIF"}`;
  return `🖼 ${att.name || "Image"}`;
}

interface ReplyPreviewBarProps {
  replyingTo: Message;
  onCancel: () => void;
}

export function ReplyPreviewBar({ replyingTo, onCancel }: ReplyPreviewBarProps) {
  const snippet =
    replyingTo.text.length > 60
      ? replyingTo.text.slice(0, 60) + "..."
      : replyingTo.text;

  return (
    <div className="flex items-center justify-between border-t border-border bg-sidebar px-4 py-2">
      <div className="flex min-w-0 flex-1 items-center gap-2">
        <Avatar
          name={replyingTo.senderName}
          size="sm"
          avatarUrl={replyingTo.senderAvatarUrl}
          avatarPreset={replyingTo.senderAvatarPreset}
        />
        <div className="min-w-0 flex-1">
          <p className="text-xs font-medium text-indigo-400">
            Replying to {replyingTo.senderName}
          </p>
          <p className="truncate text-xs text-text-secondary">{snippet}</p>
        </div>
      </div>
      <button
        onClick={onCancel}
        className="ml-2 flex-shrink-0 rounded p-1 text-text-secondary hover:bg-hover hover:text-text-primary"
      >
        <svg width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2">
          <path d="M18 6 6 18M6 6l12 12" />
        </svg>
      </button>
    </div>
  );
}

interface ReplyQuoteProps {
  replyTo?: ReplyPreview | null;
  currentUserId?: string;
}

export function ReplyQuote({ replyTo, currentUserId }: ReplyQuoteProps) {
  if (!replyTo) {
    return (
      <div className="mb-1 border-l-2 border-text-secondary pl-2">
        <p className="text-xs italic text-text-secondary">Original message was deleted</p>
      </div>
    );
  }

  // Attachment-bearing sends (new GIPHY/voice/image/file) ship with empty
  // text, and legacy GIF sends shipped with "[GIF] {title}" — both should
  // surface the attachment as the preview rather than be misread as a
  // deleted parent. Only when both fields are empty do we treat it as a
  // tombstone (the backend strips text + attachment on real deletes).
  const text = replyTo.text;
  const attachment = replyTo.attachment;
  const isLegacyGifCaption = text.startsWith("[GIF]");
  const hasUsableText = text.length > 0 && !isLegacyGifCaption;

  let snippet: string;
  let renderAsMarkdown = false;
  let isTombstone = false;

  if (hasUsableText) {
    snippet = text.length > 50 ? text.slice(0, 50) + "..." : text;
    renderAsMarkdown = true;
  } else if (attachment) {
    snippet = attachmentLabel(attachment);
  } else {
    snippet = "This message was deleted";
    isTombstone = true;
  }

  return (
    <div className="mb-1 border-l-2 border-indigo-400 pl-2">
      <div className="flex items-center gap-1.5">
        <Avatar
          name={replyTo.senderName}
          size="sm"
          avatarUrl={replyTo.senderAvatarUrl}
          avatarPreset={replyTo.senderAvatarPreset}
        />
        <p className="text-[10px] font-medium text-indigo-400">
          {replyTo.senderName}
        </p>
      </div>
      {renderAsMarkdown ? (
        <FormattedText
          text={snippet}
          className="text-xs text-text-secondary"
          mentions={replyTo.mentions}
          currentUserId={currentUserId}
        />
      ) : (
        <p
          className={`text-xs text-text-secondary ${isTombstone ? "italic" : ""}`}
        >
          {snippet}
        </p>
      )}
    </div>
  );
}
